- name: Catch if EULA has not been accepted
  fail:
    msg: "Minecraft's EULA has not been accepted. Read its EULA and set minecraft_eula to true."
  when: minecraft_eula is not true

- name: Ensure EULA is accepted in its file
  lineinfile:
    path: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/eula.txt"
    regexp: "^eula="
    line: eula=true
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
    create: true
  notify:
    - restart minecraft

- name: Ensure log4j config file is present
  copy:
    src: "files/log4j2.xml"
    dest: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/log4j2.xml"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  notify:
    - restart minecraft

- name: Ensure server.properties is set correctly
  template:
    src: templates/server.properties.j2
    dest: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/server.properties.ansible"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  notify:
    - restart minecraft
