- name: Catch if EULA has not been accepted
  fail:
    msg: "Minecraft's EULA has not been accepted. Read its EULA and set minecraft_eula to true."
  when: minecraft_eula is not true

- name: Ensure EULA is accepted in its file
  lineinfile:
    path: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/eula.txt"
    regexp: "^eula="
    line: eula=true
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
    create: true
  notify:
    - restart minecraft

- name: Ensure log4j config file is present
  copy:
    src: "files/log4j2.xml"
    dest: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/log4j2.xml"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  notify:
    - restart minecraft

- name: Ensure server.properties is set correctly
  lineinfile:
    dest: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/server.properties"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
    create: true
  loop:
    - regexp: "^enable-jmx-monitoring"
      line: "enable-jmx-monitoring={{ minecraft_prop_enable_jmx_monitoring }}"
    - regexp: "^rcon.port"
      line: "rcon.port={{ minecraft_prop_rcon_port }}"
    - regexp: "^enable-command-block"
      line: "enable-command-block={{ minecraft_prop_enable_command_block }}"
    - regexp: "^gamemode"
      line: "gamemode={{ minecraft_prop_gamemode }}"
    - regexp: "^enable-query"
      line: "enable-query={{ minecraft_prop_enable_query }}"
    - regexp: "^level-name"
      line: "level-name={{ minecraft_prop_level_name }}"
    - regexp: "^motd"
      line: "motd={{ minecraft_prop_motd }}"
    - regexp: "^query.port"
      line: "query.port={{ minecraft_prop_query_port }}"
    - regexp: "^pvp"
      line: "pvp={{ minecraft_prop_pvp }}"
    - regexp: "^difficulty"
      line: "difficulty={{ minecraft_prop_difficulty }}"
    - regexp: "^network-compression-threshold"
      line: "network-compression-threshold={{ minecraft_prop_network_compression_threshold }}"
    - regexp: "^max-tick-time"
      line: "max-tick-time={{ minecraft_prop_max_tick_time }}"
    - regexp: "^max-players"
      line: "max-players={{ minecraft_prop_max_players }}"
    - regexp: "^use-native-transport"
      line: "use-native-transport={{ minecraft_prop_use_native_transport }}"
    - regexp: "^online-mode"
      line: "online-mode={{ minecraft_prop_online_mode }}"
    - regexp: "^enable-status"
      line: "enable-status={{ minecraft_prop_enable_status }}"
    - regexp: "^allow-flight"
      line: "allow-flight={{ minecraft_prop_allow_flight }}"
    - regexp: "^broadcast-rcon-to-ops"
      line: "broadcast-rcon-to-ops={{ minecraft_prop_broadcast_rcon_to_ops }}"
    - regexp: "^view-distance"
      line: "view-distance={{ minecraft_prop_view_distance }}"
    - regexp: "^server-ip"
      line: "server-ip={{ minecraft_prop_server_ip }}"
    - regexp: "^allow-nether"
      line: "allow-nether={{ minecraft_prop_allow_nether }}"
    - regexp: "^server-port"
      line: "server-port={{ minecraft_prop_server_port }}"
    - regexp: "^enable-rcon"
      line: "enable-rcon={{ minecraft_prop_enable_rcon }}"
    - regexp: "^sync-chunk-writes"
      line: "sync-chunk-writes={{ minecraft_prop_sync_chunk_writes }}"
    - regexp: "^op-permission-level"
      line: "op-permission-level={{ minecraft_prop_op_permission_level }}"
    - regexp: "^prevent-proxy-connections"
      line: "prevent-proxy-connections={{ minecraft_prop_prevent_proxy_connections }}"
    - regexp: "^hide-online-players"
      line: "hide-online-players={{ minecraft_prop_hide_online_players }}"
    - regexp: "^entity-broadcast-range-percentage"
      line: "entity-broadcast-range-percentage={{ minecraft_prop_entity_broadcast_range_percentage }}"
    - regexp: "^simulation-distance"
      line: "simulation-distance={{ minecraft_prop_simulation_distance }}"
    - regexp: "^rcon.password"
      line: "rcon.password={{ minecraft_prop_rcon_password }}"
    - regexp: "^player-idle-timeout"
      line: "player-idle-timeout={{ minecraft_prop_player_idle_timeout }}"
    - regexp: "^force-gamemode"
      line: "force-gamemode={{ minecraft_prop_force_gamemode }}"
    - regexp: "^rate-limit"
      line: "rate-limit={{ minecraft_prop_rate_limit }}"
    - regexp: "^hardcore"
      line: "hardcore={{ minecraft_prop_hardcore }}"
    - regexp: "^white-list"
      line: "white-list={{ minecraft_prop_white_list }}"
    - regexp: "^broadcast-console-to-ops"
      line: "broadcast-console-to-ops={{ minecraft_prop_broadcast_console_to_ops }}"
    - regexp: "^spawn-npcs"
      line: "spawn-npcs={{ minecraft_prop_spawn_npcs }}"
    - regexp: "^spawn-animals"
      line: "spawn-animals={{ minecraft_prop_spawn_animals }}"
    - regexp: "^function-permission-level"
      line: "function-permission-level={{ minecraft_prop_function_permission_level }}"
    - regexp: "^text-filtering-config"
      line: "text-filtering-config={{ minecraft_prop_text_filtering_config }}"
    - regexp: "^spawn-monsters"
      line: "spawn-monsters={{ minecraft_prop_spawn_monsters }}"
    - regexp: "^enforce-whitelist"
      line: "enforce-whitelist={{ minecraft_prop_enforce_whitelist }}"
    - regexp: "^spawn-protection"
      line: "spawn-protection={{ minecraft_prop_spawn_protection }}"
    - regexp: "^max-world-size"
      line: "max-world-size={{ minecraft_prop_max_world_size }}"
    - regexp: "^resource-pack-prompt"
      line: "resource-pack-prompt={{ minecraft_prop_resource_pack_prompt }}"
    - regexp: "^require-resource-pack"
      line: "require-resource-pack={{ minecraft_prop_require_resource_pack }}"
    # - { regexp: "^resource-pack", line: "resource-pack={{ minecraft_prop_resource_pack }}" }
    # - { regexp: "^resource-pack-sha1", line: "resource-pack-sha1={{ minecraft_prop_resource_pack_sha1 }}" }
    # If you do not value your own free time. Please look into this. This is misery.
    # I dont know why. I dont understand how. But theese two options will always
    # change the file. resource-pack adds new lines for every run, while resource-pack-sha1
    # will always move itself to the bottom.
  notify:
    - restart minecraft
