---
- name: Ensure fabric jar is downloaded
  get_url:
    url: "{{ minecraft_fabric_jar.url }}"
    dest: "{{ minecraft_jars_root }}/{{ minecraft_fabric_jar.name }}"
    checksum: "{{ minecraft_fabric_jar.checksum }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"

- name: Ensure we have the server jar file symlinked
  file:
    src: "{{ minecraft_jars_root }}/{{ minecraft_fabric_jar.name }}"
    dest: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/server.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  notify:
    - restart minecraft

- name: Ensure mods folder exists
  file:
    path: "{{ minecraft_fabric_mods_folder }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: directory
    mode: "0755"

- name: Download fabric mods
  get_url:
    url: "{{ item.url }}"
    dest: "{{ minecraft_fabric_mods_folder }}/{{ item.name }}-{{ item.version }}.jar"
    checksum: "{{ item.checksum }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  with_items: "{{ minecraft_fabric_mods }}"

- name: Add symlinks to mods
  file:
    src: "{{ minecraft_fabric_mods_folder }}/{{ item.name }}-{{ item.version }}.jar"
    path: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/mods/{{ item.name }}.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  with_items: "{{ minecraft_fabric_mods }}"
  notify:
    - restart minecraft
