- name: Ensure fabric jar is downloaded
  get_url:
    url: "{{ minecraft_fabric_jar.url }}"
    dest: "{{ minecraft_jars_root }}/{{ minecraft_fabric_jar.name }}"
    checksum: "{{ minecraft_fabric_jar.checksum }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"

- name: Ensure we have the server jar file symlinked
  file:
    src: "{{ minecraft_jars_root }}/{{ minecraft_fabric_jar.name }}"
    dest: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/server.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  notify:
    - restart minecraft

- name: Ensure mods folder exists
  file:
    path: "{{ minecraft_fabric_mods_folder }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: directory
    mode: "0755"

- name: Download fabric mods
  get_url:
    url: "{{ item.url }}"
    dest: "{{ minecraft_fabric_mods_folder }}/{{ item.name }}"
    checksum: "{{ item.checksum }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  with_items: "{{ minecraft_fabric_mods }}"
  notify:
    - restart minecraft

- name: Find all symlinked mods
  find:
    path: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/mods"
    patterns: '*.jar'
    file_type: link
    recurse: false
  register: _mods_current

# TODO: Set up a validation check so we can skip resymlinking at each run.
# Below code will always run. I have put the notify check on the Downloads
# for now to give some kind of detection when a change actually occurs.
# This does not catch removal of mods from the list.

- name: Remove all symlinks to mods
  file:
    path: "{{ item.path }}"
    follow: false
    state: absent
  with_items: "{{ _mods_current.files }}"
  changed_when: false

- name: Add symlinks to mods
  file:
    src: "{{ minecraft_fabric_mods_folder }}/{{ item.name }}"
    path: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/mods/{{ item.name }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  with_items: "{{ minecraft_fabric_mods }}"
  changed_when: false
